### ISSUE TITLE
shinyashboard doesn't refresh page, it opens a new one

### ISSUE THREAD

**Issue by pablo-rodr-bio2** [ColinFay/brochure#29]
Hi
I stumbled across a question in [stackoverflow](https://stackoverflow.com/questions/70080803/shiny-router-and-shinydashboard) about creating a flow of a multipage app using tabsets inside a `shinydashboard` app .
I am able to recreate it, but when clicking on the tabname, instead of refreshing the page, it creates a new one.
Does this have something to do with the fact that `shinydashboard` adds a lot of js?

Minimal reproducible example:
```
library(shiny)
library(shinydashboard)
library(brochure)

header <- dashboardHeader(title = "Basic dashboard")
sidebar <- dashboardSidebar(
  sidebarMenu(
    menuItem("Dashboard", href = "/", icon = icon("dashboard")),
    menuItem("Widgets", href = "/widgets", icon = icon("th"))
  )
)

brochureApp(
  page(
    href="/",
    ui=dashboardPage(
      header,
      sidebar,
      dashboardBody(
        h2("Dashboard tab content")
      )
    ),
    server = function(input, output, session){}
  ),
  page(
    href="/widgets",
    ui=dashboardPage(
      header,
      sidebar,
      dashboardBody(
        h2("Widgets tab content")
      )
    ),
    server = function(input, output, session){}
  )
)
```
Just to be clear, I want to know if this issue is completely related to `shinydasboard` or you could see if there is any problem with `brochure`

Thanks!

**Comment by ColinFay** [comment]
Hey, 

Yeah the issue is that by default, `menuItem` adds `target="_blank"` to your link, which means that the link will be open in a new tab of your browser. 

![Screenshot 2022-02-22 at 20 54 46](https://user-images.githubusercontent.com/17936236/155208795-de2d7ae8-95a4-40d2-b08c-c35dfa41a0d0.png)

```r
> menuItem("Dashboard", href = "/", icon = icon("dashboard"))                                                                                                                     
<li>
  <a href="/" target="_blank">
    <i class="fa fa-dashboard" role="presentation" aria-label="dashboard icon"></i>
    <span>Dashboard</span>
  </a>
</li>
```

One hacky way to bypass this would be to do: 

```r
> it <- menuItem("Dashboard", href = "/", icon = icon("dashboard"))
> it$children[[1]]$attribs$target <- NULL 
> it
<li>
  <a href="/">
    <i class="fa fa-dashboard" role="presentation" aria-label="dashboard icon"></i>
    <span>Dashboard</span>
  </a>
</li>
```

**Comment by gueyenono** [comment]
@pablo-rodr-bio2 @ColinFay 

I'm not sure if it is a new argument to the `shinydashboard::menuItem()` function, but you have the `newtab` argument, which you can set to `FALSE` in order to cancel this behavior.
