### ISSUE TITLE
Redirect to login page

### ISSUE THREAD

**Issue by fmmattioni** [ColinFay/brochure#9]
Hey @ColinFay!

I was wondering if I could use {brochure} for a redirect to a login page? I am looking for a way to integrate [AWS Cognito](https://aws.amazon.com/cognito/) in a {golem} app, and I still haven't found a good package or resource to do that. I was wondering if I could use {brochure} to make my own redirect to the login page?

Thanks in advance!
Felipe

**Comment by ColinFay** [comment]
Hey, 

Sorry for the late reply. 

If your login is inside shiny, that would definitely be what you are looking for: 
- a page at /
- a login at /login, which redirect in case of successful connection using `brochure::redirect()` from the server side. 
- You might need to use some kind of token (for example as a query string) as a cookie, as described in the Readme in https://github.com/ColinFay/brochure#handling-cookies-using-res_handlers

Let me know your thoughts, 

Colin

**Comment by fmmattioni** [comment]
Hey Colin!

This is fantastic! I am going to give it a try!! Thank you!

**Comment by ColinFay** [comment]
Closing this, I suppose this is solved,  let me know :)
